# Generated by Django 4.1.7 on 2023-03-26 15:13

import accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generation',
            name='brand',
        ),
        migrations.AddField(
            model_name='generation',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.model'),
        ),
        migrations.AddField(
            model_name='generation',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.nameFile),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.nameFile),
        ),
        migrations.AlterField(
            model_name='car',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.nameFile),
        ),
    ]
