version: '3.9'

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mediasoft
      - POSTGRES_USER=mediasoft
      - POSTGRES_PASSWORD=Mediasoft@2023
    ports:
      - 5433:5432

  web:
    build:
      context: .
    command: > 
      sh -c python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"

